#! /bin/bash

ls /media/gab/Elements

if [ $? = 0 ]; then
	rsync -avu --delete-after /media/gab/Data/myCloud/Archives /media/gab/Elements/Gab > ~/bkp-archives.log
else
	echo "Destination not found"
fi


