#! /bin/bash

# FSTAB: //internetbox-nas/Elements      /media/gab/Elements     cifs     guest,iocharset=utf8,gid=100,uid=1000,_netdev,sec=ntlm,vers=1.0     0       0
ls /media/gab/Elements

if [ $? = 0 ]; then
	rsync -avu --delete /media/gab/Data/myCloud/ /media/gab/Elements/Gab > ~/bkp-data.log
else
	echo "Destination not found"
fi


