#! /bin/bash

src=$1
dest=$2

rsync -av --cvs-exclude --include 'view_default/' --exclude 'view_*/' $src'/admin/' $dest'/admin'
rsync -av --cvs-exclude --include 'view_default/' --exclude 'view_*/' $src'/common/' $dest'/common'
rsync -av --cvs-exclude $src'/core/' $dest'/core' 
rsync -av --cvs-exclude --include 'view_default/' --exclude 'view_*/' $src'/modules/default/' $dest'/modules/default'
rsync -av --cvs-exclude $src'/install/' $dest'/install'
rsync -av --cvs-exclude $src'/plugins/' $dest'/plugins'
rsync -av $src'/cron.php' $dest'/'
rsync -av $src'/cache/.htaccess' $dest'/cache/'

